language: python
cache: pip
dist: xenial
python:
  - 3.7
install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install pytest pytest-cov wheel codecov --upgrade
  - python3 setup.py bdist_wheel
  - pip install dist/pennylane_extra*.whl
script:
  - make coverage
after_success:
  - codecov